version: "3"

tasks:
  gen:
    desc: Generate all code via Docker
    cmds:
      - docker build -t protos-sso-gen -f DockerfileGenProto .
      - rm -rf gen/ts gen/go gen/openapi

      - docker run --rm -v {{.PWD}}:/workspace protos-sso-gen buf generate --template buf.gen.go.yaml

      - docker run --rm -v {{.PWD}}:/workspace protos-sso-gen buf generate --template buf.gen.ts.yaml --path proto/sso/api

  lint:
    cmds:
      - buf lint proto

  deps:
    cmds:
      - buf mod update proto
